trigger:
  branches:
    include:
      - main

variables:
  buildConfiguration: Release
  azureSubscription: 'Azure subscription 1'
  appName: 'prajwal-l1-webapp'

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    version: 6.x

- script: dotnet restore
  displayName: Restore

- script: dotnet build --configuration $(buildConfiguration)
  displayName: Build

- script: dotnet publish -c $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: Publish

- task: AzureWebApp@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: $(Build.ArtifactStagingDirectory)
